### ISSUE TITLE
手机浏览器只能一直打开才能使用，后台后的各种问题大佬有没有方案

### ISSUE THREAD

**Issue by 313319569** [egdw/SyncMusic#1]
如，uc浏览器 安卓版播放一顿一顿的，然后就是播放完一首歌之后，后台js无法执行播放下一首之类的。

**Comment by egdw** [comment]
这个问题我也注意到了，最近也很忙。之前打了一个版本用websocket 的方式实现，不知道会不会有好用点。还没有打完，最近有点忙
