### ISSUE TITLE
$.getJSON提示跨域

### ISSUE THREAD

**Issue by JumpAlang** [egdw/SyncMusic#3]
Music.vue中的$.getJSON请求https://163.fczbl.vip/playlist/detail?id=2339591623，提示跨域

**Comment by egdw** [comment]
> 最近比较忙,项目暂停维护

这个问题我已经知晓.请先使用我前一段时间做的基于websocket的同步听歌.后续我有空了再维护.
[websocket情侣同步听歌](http://egdw.coding.me/SyncMusicForWebSocket/#/music/playlist)

**Comment by JumpAlang** [comment]
> > 最近比较忙,项目暂停维护
> 
> 这个问题我已经知晓.请先使用我前一段时间做的基于websocket的同步听歌.后续我有空了再维护.
> [websocket情侣同步听歌](http://egdw.coding.me/SyncMusicForWebSocket/#/music/playlist)

这个websocket很强大 ，可是不是房主不能点歌

**Comment by egdw** [comment]
> > > 最近比较忙,项目暂停维护
> > 
> > 
> > 这个问题我已经知晓.请先使用我前一段时间做的基于websocket的同步听歌.后续我有空了再维护.
> > [websocket情侣同步听歌](http://egdw.coding.me/SyncMusicForWebSocket/#/music/playlist)
> 
> 这个websocket很强大 ，可是不是房主不能点歌

目前是的.因为我没有想好多个用户之间的同步.不想好的话容易出现两边死循环.理论上是可以同时两边修改的.

**Comment by JumpAlang** [comment]
> > > > 最近比较忙,项目暂停维护
> > > 
> > > 
> > > 这个问题我已经知晓.请先使用我前一段时间做的基于websocket的同步听歌.后续我有空了再维护.
> > > [websocket情侣同步听歌](http://egdw.coding.me/SyncMusicForWebSocket/#/music/playlist)
> > 
> > 
> > 这个websocket很强大 ，可是不是房主不能点歌
> 
> 目前是的.因为我没有想好多个用户之间的同步.不想好的话容易出现两边死循环.理论上是可以同时两边修改的.

一起研究下。
