### ISSUE TITLE
搭建了服务器但无法进行歌曲同步

### ISSUE THREAD

**Issue by fraelyfan** [egdw/SyncMusic#6]
这个问题是基于：https://github.com/egdw/Vue-mmPlayer 项目的
你好我搭建了服务器但无法进行歌曲同步
我发现好像ws替换服务器的IP还在访问以前你架设的服务器
能提供一下在哪里替换IP的地方吗

**Comment by egdw** [comment]
https://github.com/egdw/Vue-mmPlayer/blob/master/src/pages/music.vue

**Comment by egdw** [comment]
393行

**Comment by fraelyfan** [comment]
> 393行

非常感谢
