### ISSUE TITLE
http://132.232.148.31:8080/#/Music/exf0k/1进入过后只有开始使用界面

### ISSUE THREAD

**Issue by gongrong1226** [egdw/SyncMusic#7]
在自己的服务器上按照README中npm install和nmp run dev搭建运行过后。进入网页只有“开始使用”，然后就什么反应都没有了，怎么回事呢，怎么解决，谢谢！

**Comment by egdw** [comment]
您好,
问题在于音乐接口失效了,由于长时间不维护导致原本用别人的接口失效了之后就无法在使用了.
你可以使用基于websocket方式的同步听歌,https://github.com/egdw/Vue-mmPlayer
或者通过修改代码当中的https://163.fczbl.vip/ 域名改成其他能够正常解析的域名.
如果你有服务器的话
https://github.com/Binaryify/NeteaseCloudMusicApi
用下面这个搭建,然后把上面的域名替换成为你自己搭建的服务器应该就能用了.
或者你可以去google和baidu上找.关键词是网易云音乐api.
例如下面的网站:
https://music.aityp.com/

**Comment by egdw** [comment]
强烈推荐基于websocket的方式,但是最近一段时间没有时间去整理文档.前端是通过vue.js写的.
但是地址也是写死在里面的,由于我的服务器已经关停.你需要自己搭建好服务器.然后修改成你自己的地址.然后在编译完成的网页放在gitpage上或者其他上都可以.稳定而且高效.界面我用的别人做好的,然后自己加了同步的代码.更方便.

**Comment by egdw** [comment]
具体websocket的方式在哪里改地址你可以看我那个项目上的issus.里面之前有人问过了,我已经给出解答了.

**Comment by gongrong1226** [comment]
如此详细，非常非常感谢您的热心！

**Comment by gongrong1226** [comment]
> 具体websocket的方式在哪里改地址你可以看我那个项目上的issus.里面之前有人问过了,我已经给出解答了.

这个项目换了api就能用了，只有有些瑕疵。我现在打算用您基于的websocket的那个项目试试，抱歉我没有在那个项目看到issue，所以不清楚在哪里更改，能详细描述一下吗？拜托🥺

**Comment by egdw** [comment]
https://github.com/egdw/SyncMusic/issues/6
