### ISSUE TITLE
一起听歌吧来接棒，欢迎大家过来一起同步听歌，分享音乐、聊天互动

### ISSUE THREAD

**Issue by JumpAlang** [egdw/SyncMusic#8]
一起听歌吧支持多人同步听歌、分享音乐、聊天、歌单搜索、歌曲搜索。欢迎各圈人士创建属于你们的音乐屋。
最主要的是适配手机端，目前有提供安卓版本下载。
马上食用：<http://music.alang.run>

我一直有个想法，我可以分享我的音乐到校园点歌台
我一直有个想法，我可以分享我的音乐到我最喜欢去的奶茶店
我一直有个想法，我可以分享我的音乐予志同道合的人
我相信一起听歌吧可以实现这些想法
![1](https://user-images.githubusercontent.com/25969133/86991989-05ee8780-c1d3-11ea-8d70-169fff588011.jpg)
![2](https://user-images.githubusercontent.com/25969133/86991992-08e97800-c1d3-11ea-9dfc-72a94f4924f5.jpg)
![3](https://user-images.githubusercontent.com/25969133/86991995-0ab33b80-c1d3-11ea-90ad-d225b0b6e491.jpg)

**Comment by egdw** [comment]
可以的，界面不错。不知道效果如何

**Comment by egdw** [comment]
你这个创建房间那里和背景融为一体，看不太清楚。建议改一改

**Comment by JumpAlang** [comment]
> 你这个创建房间那里和背景融为一体，看不太清楚。建议改一改
是指这个吗？
![1](https://user-images.githubusercontent.com/25969133/86992464-1ce1a980-c1d4-11ea-80f7-bdda959fbbfc.png)

**Comment by egdw** [comment]
> > 你这个创建房间那里和背景融为一体，看不太清楚。建议改一改
> > 是指这个吗？
> > ![1](https://user-images.githubusercontent.com/25969133/86992464-1ce1a980-c1d4-11ea-80f7-bdda959fbbfc.png)

是的
